"use client";

import { useMemo } from "react";
import { PEN, StrokeInView } from "./Ink";
import { inkArrow } from "@/lib/ink";
import { rngFrom } from "@/lib/prng";

/**
 * Something written in the margin, with an arrow to what it's about.
 *
 * The cheapest thing that makes a page of data look *authored*. A chart
 * with axis labels was generated by something; a chart somebody went back
 * over afterwards and had opinions about was made by someone, and the
 * difference is one layer of scrawl. It's also the only honest place for
 * momm's voice to sit next to a number — a caption underneath reads as
 * the site talking, a note in the margin reads as her.
 *
 * The arrow is a self-contained SVG at a fixed size rather than a line
 * computed between two page coordinates. Measuring across from a DOM node
 * to a point inside a chart's viewBox means a layout read on every resize
 * for something the eye reads as "roughly over there" — and eight
 * directions cover every placement this page actually needs.
 */

export type ArrowDir = "down" | "down-left" | "down-right" | "left" | "right" | "up-left" | "up-right" | "up";

const A = 96;

/** where the arrow leaves the note, and where it lands, within a 96² box */
const ENDS: Record<ArrowDir, [[number, number], [number, number]]> = {
  down: [[48, 8], [46, 88]],
  "down-left": [[86, 10], [12, 84]],
  "down-right": [[10, 10], [84, 84]],
  left: [[88, 44], [10, 52]],
  right: [[8, 44], [86, 52]],
  "up-left": [[86, 86], [12, 12]],
  "up-right": [[10, 86], [84, 12]],
  up: [[48, 88], [46, 8]],
};

export default function Annotation({
  children,
  dir = "down",
  seed = "note",
  delay = 0,
  className = "",
  /** the arrow sits after the text for downward aims, before it for upward */
  reverse,
}: {
  children: React.ReactNode;
  dir?: ArrowDir;
  seed?: string;
  delay?: number;
  className?: string;
  reverse?: boolean;
}) {
  const paths = useMemo(() => {
    const [from, to] = ENDS[dir];
    return inkArrow(
      { x: from[0], y: from[1] },
      { x: to[0], y: to[1] },
      {
        seed: `${seed}:arrow`,
        // a hand-drawn arrow that curves the same way twice on one page
        // stops reading as handwriting, so the bow comes off the seed
        curve: 0.14 + rngFrom(`${seed}:bow`)() * 0.16,
        amp: 1.3,
      },
    );
  }, [dir, seed]);

  const arrowUp = reverse ?? dir.startsWith("up");
  const arrow = (
    <svg
      viewBox={`0 0 ${A} ${A}`}
      className="h-16 w-16 shrink-0 md:h-20 md:w-20"
      aria-hidden
      focusable="false"
    >
      {paths.map((d, i) => (
        <StrokeInView
          key={i}
          d={d}
          stroke={PEN.ink}
          strokeWidth={2}
          speed={i === 0 ? 620 : 240}
          delay={delay + (i === 0 ? 0 : 560)}
          amount={0.3}
        />
      ))}
    </svg>
  );

  return (
    <div
      className={`pointer-events-none flex max-w-[15rem] flex-col items-start gap-1 ${className}`}
    >
      {arrowUp && arrow}
      <p
        className="font-hand text-xl leading-tight md:text-2xl"
        style={{ color: PEN.ink }}
      >
        {children}
      </p>
      {!arrowUp && arrow}
    </div>
  );
}
