/**
 * Phase 0 — avatar pipeline.
 * Reads the 2048² PNG originals, trims the transparent padding (so the
 * character fills its box and the contact shadow lands at the feet),
 * fits inside 512, writes WebP + a typed manifest.
 * Originals are left untouched.
 */
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const ROOT = "c:/Users/abhap/Downloads/momm/momm-website";
const SRC = path.join(ROOT, "public/momm-avatars");
const OUT = path.join(ROOT, "public/avatars");
const MAX = 512;

(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  const files = fs.readdirSync(SRC).filter((f) => f.endsWith(".png")).sort();
  const manifest = {};
  let before = 0;
  let after = 0;

  for (const file of files) {
    const name = path.basename(file, ".png");
    const srcPath = path.join(SRC, file);
    before += fs.statSync(srcPath).size;

    const out = path.join(OUT, name + ".webp");
    const info = await sharp(srcPath)
      .trim({ threshold: 1 }) // alpha-based: top-left pixel is transparent
      .resize({
        width: MAX,
        height: MAX,
        fit: "inside",
        withoutEnlargement: true,
      })
      .webp({ quality: 90, effort: 6 })
      .toFile(out);

    after += info.size;
    manifest[name] = { w: info.width, h: info.height };
    console.log(
      `${name.padEnd(32)} ${String(info.width).padStart(4)}x${String(info.height).padEnd(4)}  ${(info.size / 1024).toFixed(0)}kb`,
    );
  }

  const ts =
    `/**\n` +
    ` * Generated by scripts/optimize-avatars.js — do not edit by hand.\n` +
    ` * Intrinsic (trimmed) dimensions of every avatar, so <Avatar> can\n` +
    ` * reserve the right box and never shift layout on load.\n` +
    ` */\n` +
    `export const AVATARS = ${JSON.stringify(manifest, null, 2)} as const;\n\n` +
    `export type AvatarName = keyof typeof AVATARS;\n`;
  fs.writeFileSync(path.join(ROOT, "src/avatars.ts"), ts);

  console.log(
    `\n${files.length} avatars · ${(before / 1e6).toFixed(1)}MB -> ${(after / 1e6).toFixed(2)}MB ` +
      `(${(100 - (after / before) * 100).toFixed(1)}% smaller)`,
  );
})();
