/**
 * Generated by scripts/optimize-avatars.js — do not edit by hand.
 * Intrinsic (trimmed) dimensions of every avatar, so <Avatar> can
 * reserve the right box and never shift layout on load.
 */
export const AVATARS = {
  "kid-guilty": {
    "w": 343,
    "h": 512
  },
  "kid-happy": {
    "w": 404,
    "h": 512
  },
  "kid-neutral": {
    "w": 305,
    "h": 512
  },
  "kid-sad": {
    "w": 476,
    "h": 512
  },
  "kid-showing-mom-hobby-proud": {
    "w": 512,
    "h": 494
  },
  "momm-encouraging": {
    "w": 391,
    "h": 512
  },
  "momm-happy": {
    "w": 356,
    "h": 512
  },
  "momm-kid-celebrating": {
    "w": 473,
    "h": 512
  },
  "momm-kid-hugging": {
    "w": 340,
    "h": 512
  },
  "momm-neutral": {
    "w": 261,
    "h": 512
  },
  "momm-offering-a-hand": {
    "w": 277,
    "h": 512
  },
  "momm-proud": {
    "w": 251,
    "h": 512
  },
  "momm-showing-kid-hobby": {
    "w": 509,
    "h": 512
  },
  "momm-smirking": {
    "w": 240,
    "h": 512
  },
  "momm-suggesting": {
    "w": 479,
    "h": 512
  },
  "momm-teaching-kid-hobby": {
    "w": 466,
    "h": 512
  }
} as const;

export type AvatarName = keyof typeof AVATARS;
